export const typosquatts = [
  '4equest',
  'bzip',
  'crypt',
  'dajngo',
  'dequests',
  'diango',
  'djago',
  'douctils',
  'falsk',
  'fequests',
  'gequests',
  'gesnim',
  'inda',
  'ipaddres',
  'ipadress',
  'jeIlyfish',
  'kears',
  'Kears',
  'lxlm',
  'mokc',
  'mplatlib',
  'pkgutil',
  'pymafka',
  'python3-dateutil',
  'r1quests',
  'r3quests',
  'r4quests',
  'r5quests',
  'rdquests',
  'reauests',
  'reduests',
  'reeuests',
  'req7ests',
  'req8ests',
  'reqhests',
  'reqkests',
  'requesfs',
  'requesr',
  'requesrs',
  'requesta',
  'requeste',
  'requestw',
  'requesys',
  'requfsts',
  'resuests',
  'rewuests',
  'rfquests',
  'rrquests',
  'rwquests',
  'seabron',
  'setup-tools',
  'smplejson',
  'tensorfolw',
  'tequests',
  'timeit',
  'tqmd',
  'urlib3',
  'urllib',
  'Xcryptography',
];

export const packageManifest = {
  info: {
    author: 'Django Software Foundation',
    author_email: 'foundation@djangoproject.com',
    bugtrack_url: null,
    classifiers: [
      'Development Status :: 5 - Production/Stable',
      'Environment :: Web Environment',
      'Framework :: Django',
      'Intended Audience :: Developers',
      'License :: OSI Approved :: BSD License',
      'Operating System :: OS Independent',
      'Programming Language :: Python',
      'Programming Language :: Python :: 3',
      'Programming Language :: Python :: 3 :: Only',
      'Programming Language :: Python :: 3.10',
      'Programming Language :: Python :: 3.11',
      'Programming Language :: Python :: 3.8',
      'Programming Language :: Python :: 3.9',
      'Topic :: Internet :: WWW/HTTP',
      'Topic :: Internet :: WWW/HTTP :: Dynamic Content',
      'Topic :: Internet :: WWW/HTTP :: WSGI',
      'Topic :: Software Development :: Libraries :: Application Frameworks',
      'Topic :: Software Development :: Libraries :: Python Modules',
    ],
    description:
      "======\nDjango\n======\n\nDjango is a high-level Python web framework that encourages rapid development\nand clean, pragmatic design. Thanks for checking it out.\n\nAll documentation is in the \"``docs``\" directory and online at\nhttps://docs.djangoproject.com/en/stable/. If you're just getting started,\nhere's how we recommend you read the docs:\n\n* First, read ``docs/intro/install.txt`` for instructions on installing Django.\n\n* Next, work through the tutorials in order (``docs/intro/tutorial01.txt``,\n  ``docs/intro/tutorial02.txt``, etc.).\n\n* If you want to set up an actual deployment server, read\n  ``docs/howto/deployment/index.txt`` for instructions.\n\n* You'll probably want to read through the topical guides (in ``docs/topics``)\n  next; from there you can jump to the HOWTOs (in ``docs/howto``) for specific\n  problems, and check out the reference (``docs/ref``) for gory details.\n\n* See ``docs/README`` for instructions on building an HTML version of the docs.\n\nDocs are updated rigorously. If you find any problems in the docs, or think\nthey should be clarified in any way, please take 30 seconds to fill out a\nticket here: https://code.djangoproject.com/newticket\n\nTo get more help:\n\n* Join the ``#django`` channel on ``irc.libera.chat``. Lots of helpful people\n  hang out there. See https://web.libera.chat if you're new to IRC.\n\n* Join the django-users mailing list, or read the archives, at\n  https://groups.google.com/group/django-users.\n\nTo contribute to Django:\n\n* Check out https://docs.djangoproject.com/en/dev/internals/contributing/ for\n  information about getting involved.\n\nTo run Django's test suite:\n\n* Follow the instructions in the \"Unit tests\" section of\n  ``docs/internals/contributing/writing-code/unit-tests.txt``, published online at\n  https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/unit-tests/#running-the-unit-tests\n\nSupporting the Development of Django\n====================================\n\nDjango's development depends on your contributions. \n\nIf you depend on Django, remember to support the Django Software Foundation: https://www.djangoproject.com/fundraising/\n",
    description_content_type: '',
    docs_url: null,
    download_url: '',
    downloads: { last_day: -1, last_month: -1, last_week: -1 },
    home_page: 'https://www.djangoproject.com/',
    keywords: '',
    license: 'BSD-3-Clause',
    maintainer: '',
    maintainer_email: '',
    name: 'Django',
    package_url: 'https://pypi.org/project/Django/',
    platform: null,
    project_url: 'https://pypi.org/project/Django/',
    project_urls: {
      Documentation: 'https://docs.djangoproject.com/',
      Funding: 'https://www.djangoproject.com/fundraising/',
      Homepage: 'https://www.djangoproject.com/',
      'Release notes': 'https://docs.djangoproject.com/en/stable/releases/',
      Source: 'https://github.com/django/django',
      Tracker: 'https://code.djangoproject.com/',
    },
    release_url: 'https://pypi.org/project/Django/4.2.2/',
    requires_dist: [
      'asgiref (<4,>=3.6.0)',
      'sqlparse (>=0.3.1)',
      'backports.zoneinfo ; python_version < "3.9"',
      'tzdata ; sys_platform == "win32"',
      "argon2-cffi (>=19.1.0) ; extra == 'argon2'",
      "bcrypt ; extra == 'bcrypt'",
    ],
    requires_python: '>=3.8',
    summary: 'A high-level Python web framework that encourages rapid development and clean, pragmatic design.',
    version: '4.2.2',
    yanked: false,
    yanked_reason: null,
  },
  last_serial: 18377009,
  releases: {
    '1.1.3': [
      {
        comment_text: '',
        digests: {
          blake2b_256: '8f1f74aa91b56dea5847b62e11ce6737db82c6446561bddc20ca80fa5df025cc',
          md5: '52848c23dbc120fe0b2a8e7189b20306',
          sha256: '0e5034cf8046ba77c62e95a45d776d2c59998b26f181ceaf5cec516115e3f85a',
        },
        downloads: -1,
        filename: 'Django-1.1.3.tar.gz',
        has_sig: false,
        md5_digest: '52848c23dbc120fe0b2a8e7189b20306',
        packagetype: 'sdist',
        python_version: 'source',
        requires_python: null,
        size: 5748608,
        upload_time: '2010-12-23T05:14:23',
        upload_time_iso_8601: '2010-12-23T05:14:23.509436Z',
        url: 'https://files.pythonhosted.org/packages/8f/1f/74aa91b56dea5847b62e11ce6737db82c6446561bddc20ca80fa5df025cc/Django-1.1.3.tar.gz',
        yanked: false,
        yanked_reason: null,
      },
    ],
  },
  urls: [
    {
      comment_text: '',
      digests: {
        blake2b_256: 'baf37a66888bda4017198a692887bd566123732783073c1fd424db15358525fd',
        md5: '5bff9e117350e5d80fd10209a1c38efd',
        sha256: '672b3fa81e1f853bb58be1b51754108ab4ffa12a77c06db86aa8df9ed0c46fe5',
      },
      downloads: -1,
      filename: 'Django-4.2.2-py3-none-any.whl',
      has_sig: false,
      md5_digest: '5bff9e117350e5d80fd10209a1c38efd',
      packagetype: 'bdist_wheel',
      python_version: 'py3',
      requires_python: '>=3.8',
      size: 7989179,
      upload_time: '2023-06-05T14:09:31',
      upload_time_iso_8601: '2023-06-05T14:09:31.615719Z',
      url: 'https://files.pythonhosted.org/packages/ba/f3/7a66888bda4017198a692887bd566123732783073c1fd424db15358525fd/Django-4.2.2-py3-none-any.whl',
      yanked: false,
      yanked_reason: null,
    },
    {
      comment_text: '',
      digests: {
        blake2b_256: '5cfa427fbcac5633f4b88fda7953efb04db903ca7e6d9486afdbda525c4006cc',
        md5: '17feee0fb1ddfcb0144c6362fd53ffca',
        sha256: '2a6b6fbff5b59dd07bef10bcb019bee2ea97a30b2a656d51346596724324badf',
      },
      downloads: -1,
      filename: 'Django-4.2.2.tar.gz',
      has_sig: false,
      md5_digest: '17feee0fb1ddfcb0144c6362fd53ffca',
      packagetype: 'sdist',
      python_version: 'source',
      requires_python: '>=3.8',
      size: 10390518,
      upload_time: '2023-06-05T14:09:38',
      upload_time_iso_8601: '2023-06-05T14:09:38.470129Z',
      url: 'https://files.pythonhosted.org/packages/5c/fa/427fbcac5633f4b88fda7953efb04db903ca7e6d9486afdbda525c4006cc/Django-4.2.2.tar.gz',
      yanked: false,
      yanked_reason: null,
    },
  ],
  vulnerabilities: [],
};
