# This is a basic workflow to help you get started with Actions
name: Workflow Run

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  workflow_run:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          name: diagrams
          path: packages/examples/diagrams/
          persist-credentials: true
      - name: Record performance summary
        working-directory: packages/examples/diagrams/
        run: |
          set -x

          echo '#Performance' >> $GITHUB_STEP_SUMMARY
          echo >> $GITHUB_STEP_SUMMARY
          cat stats.md >> $GITHUB_STEP_SUMMARY          
      - uses: actions/upload-artifact@v4
        with:
          name: diagrams
          path: packages/examples/diagrams/
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
     - run : echo "Deploying"  
